package entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.id
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.username
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.password
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.email
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.phone
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.create_time
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.update_time
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_user.role
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.id
     *
     * @return the value of shop_user.id
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.id
     *
     * @param id the value for shop_user.id
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.username
     *
     * @return the value of shop_user.username
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.username
     *
     * @param username the value for shop_user.username
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.password
     *
     * @return the value of shop_user.password
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.password
     *
     * @param password the value for shop_user.password
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.email
     *
     * @return the value of shop_user.email
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.email
     *
     * @param email the value for shop_user.email
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.phone
     *
     * @return the value of shop_user.phone
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.phone
     *
     * @param phone the value for shop_user.phone
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.create_time
     *
     * @return the value of shop_user.create_time
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.create_time
     *
     * @param createTime the value for shop_user.create_time
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.update_time
     *
     * @return the value of shop_user.update_time
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.update_time
     *
     * @param updateTime the value for shop_user.update_time
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_user.role
     *
     * @return the value of shop_user.role
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_user.role
     *
     * @param role the value for shop_user.role
     *
     * @mbg.generated Thu Sep 13 10:42:15 CST 2018
     */
    public void setRole(Integer role) {
        this.role = role;
    }
}